package br.edu.sr.ifes.mpn.model;

import br.edu.sr.ifes.mpn.model.*;

rule "PacienteNaoDoadorTime"
	when 
	 	$n: Notificacao($o: Obito)
	 	$n1: Notificacao(this == $n, getDelayTime() > 21600000)
	 	
	then
	 	System.out.println ("---> Paciente Inápito! notificação de codigo: -----> "+ $n.getCodigo()+ " não pode ser tratado como possivel doador!"); 
	 	retract($n)
end

rule "PacienteNaoDoadorDoenca"
	when 
	 	$n: Notificacao($o: Obito)
	 	$o1: Obito(this == $o, $c: CausaMortis)
	 	$c1: CausaMortis(this == $c, tipoMorte == TipoMorte.DoencaContagiosa)
	 	
	then
	 	System.out.println ("---> Paciente com Doença Contagiosa! notificação de codigo: -----> "+ $n.getCodigo()+ " não pode ser tratado como possivel doador!"); 
	 	retract($n)
end

rule "PacienteDoador"
	when 
	 	$n: Notificacao()
	then
	 	System.out.println ("---> Notificação de codigo: -----> "+ $n.getCodigo()+ " agendar entrevista, possivel doador!"); 
	 	Doacao doacao = new Doacao();
        doacao.setAutorizado(true);
        doacao.setMotivoRecusa(null);
        doacao.setObito($n.getObito());
        doacao.setDataEntradaDoacao();
        insert(doacao);
	 	
end

rule "DoacaoNegada"
	when 
		$n: Notificacao($o: Obito)
	 	$d: Doacao($o2: Obito,  autorizado == false)
	 	$o3: Obito(this == $o, $o3 == $o2)
	then
	 	System.out.println ("---> Doação Negada! "+ $d.getMotivoRecusa());
	 	retract($d)
	 	retract($n) 
end

rule "DoacaoAceitaComTempoEsgotado"
	when
		$n: Notificacao($o: Obito)
		$d: Doacao($o2: Obito, autorizado == true)
	 	$o3: Obito(this == $o, $o3 == $o2)
	 	$d1: Doacao(this == $d, getDelayTime() > 21600000)
	 	
	 	
	then
	 	System.out.println ("---> Doação Aceita, mas o tempo para o processo já está no limite! Paciente Invalido!");
	    retract($d)
	 	retract($n) 
end

rule "DoacaoAceita"
	when
		$n: Notificacao($o: Obito)
	 	$d: Doacao(obito == $o)
	then
	 	System.out.println ("---> Doação Aceita! Avisar Banco de olhos! ");
	 	Captacao captacao = new Captacao();
        captacao.setDoacao($d);
        captacao.setDataEntradaCaptacao();
        insert(captacao);
end

rule "Obito em Vitoria"
	when 
	 	$c: Captacao($d: Doacao, realizada == false)
	 	$d1: Doacao(this == $d, $o : Obito)
	 	$o1: Obito(this == $o, localMorte == LocalMorte.Vitoria) 
	 	$i: Instituicao(sigla == "vix")
	then
	 	System.out.println ("---> Banco de Olhos Jayme! ");
	 	$c.setRealizada(true);	 	
	 	update($c);
	 	$i.addItenInThelist($c);
	 	update($i);
end
